export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const LOGIN_ADMIN_LOADING = 'LOGIN_ADMIN_LOADING';
export const LOGIN_ADMIN_LOADING_STOP = 'LOGIN_ADMIN_LOADING_STOP';