export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_MURID= 'SET_CURRENT_MURID';
export const LOGIN_MURID_LOADING = 'LOGIN_MURID_LOADING';
export const LOGIN_MURID_LOADING_STOP = 'LOGIN_MURID_LOADING_STOP';

export const SET_NEW_MURID = 'SET_NEW_MURID';
export const GET_ALL_MURID = 'GET_ALL_MURID';

export const RAPOT_MURID_LOADING = 'RAPOT_MURID_LOADING';
export const GET_RAPOT_MURID = 'GET_RAPOT_MURID';
export const GET_RAPOT_MURID_LOADING = 'GET_RAPOT_MURID_LOADING';
export const GET_DATA_RAPOT_MURID = 'GET_DATA_RAPOT_MURID';
export const IMPORT_RAPOT_MURID = 'IMPORT_RAPOT_MURID';
export const IMPORT_LOADING = 'IMPORT_LOADING';
export const RAPOT_LIST = 'RAPOT_LIST';

export const GET_LAST_KODEPERTANYAAN = 'GET_LAST_KODEPERTANYAAN';
export const LOADING_CREATE_PERTANYAAN = 'LOADING_CREATE_PERTANYAAN';
export const SET_NEW_PERTANYAAN = 'SET_NEW_PERTANYAAN';
export const GET_ALL_PERTANYAAN = 'GET_ALL_PERTANYAAN';
export const DELETE_PERTANYAAN = 'DELETE_PERTANYAAN';
export const GET_PERTANYAAN = 'GET_PERTANYAAN';


// JURUSAN
export const LOADING_JURUSAN = 'LOADING_JURUSAN';
export const GET_ALL_JURUSAN = 'GET_ALL_JURUSAN';
export const DELETE_JURUSAN = 'DELETE_JURUSAN';
export const GET_JURUSAN = 'GET_JURUSAN';

// Konsultasi
export const GET_QUESTION_KONSULTASI = 'GET_QUESTION_KONSULTASI';
export const LOADING_NEXT_QUESTION_KONSULTASI = 'LOADING_NEXT_QUESTION_KONSULTASI'
export const GET_JAWABAN_KONSULTASI = 'GET_JAWABAN_KONSULTASI';
export const RESET_JAWABAN_KONSULTASI ="RESET_JAWABAN_KONSULTASI";